[package]
name = "reprehensible"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"
description = "experimental authenticated and encrypted unordered datagrams"
license = "MIT OR Apache-2.0"

[dependencies]
x25519-dalek = "0.5.2"
rand_os = "0.1.3"
